// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_test

import (
	context "context"

	domain "github.com/avito-internships/test-backend-1-mmms914/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SlotRepository is an autogenerated mock type for the SlotRepository type
type SlotRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, slotID
func (_m *SlotRepository) GetByID(ctx context.Context, slotID uuid.UUID) (*domain.Slot, error) {
	ret := _m.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Slot, error)); ok {
		return rf(ctx, slotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Slot); ok {
		r0 = rf(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSlotRepository creates a new instance of SlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotRepository {
	mock := &SlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
