// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_test

import (
	context "context"

	domain "github.com/mmms914/test-avito-internship/internal/domain"
	dto "github.com/mmms914/test-avito-internship/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetAvailableSlots provides a mock function with given fields: ctx, f
func (_m *Service) GetAvailableSlots(ctx context.Context, f *dto.SlotFilter) ([]*domain.Slot, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSlots")
	}

	var r0 []*domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) ([]*domain.Slot, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) []*domain.Slot); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SlotFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
