// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avito-internships/test-backend-1-mmms914/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, schedule
func (_m *Repository) Create(ctx context.Context, schedule *domain.Schedule) (*domain.Schedule, error) {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Schedule) (*domain.Schedule, error)); ok {
		return rf(ctx, schedule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Schedule) *domain.Schedule); ok {
		r0 = rf(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Schedule) error); ok {
		r1 = rf(ctx, schedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
