// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_test

import (
	context "context"

	domain "github.com/avito-internships/test-backend-1-mmms914/internal/domain"
	dto "github.com/avito-internships/test-backend-1-mmms914/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Repository) Create(ctx context.Context, _a1 []*domain.Slot) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Slot) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAvailable provides a mock function with given fields: ctx, f
func (_m *Repository) GetAllAvailable(ctx context.Context, f *dto.SlotFilter) ([]*domain.Slot, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAvailable")
	}

	var r0 []*domain.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) ([]*domain.Slot, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) []*domain.Slot); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SlotFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSlotsExist provides a mock function with given fields: ctx, f
func (_m *Repository) IsSlotsExist(ctx context.Context, f *dto.SlotFilter) (bool, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for IsSlotsExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) (bool, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SlotFilter) bool); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SlotFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
