// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_test

import (
	context "context"

	domain "github.com/avito-internships/test-backend-1-mmms914/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type ScheduleRepository struct {
	mock.Mock
}

// GetForRoom provides a mock function with given fields: ctx, roomID
func (_m *ScheduleRepository) GetForRoom(ctx context.Context, roomID uuid.UUID) (*domain.Schedule, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetForRoom")
	}

	var r0 *domain.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Schedule, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Schedule); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScheduleRepository creates a new instance of ScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleRepository {
	mock := &ScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
