// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks_test

import (
	context "context"

	domain "github.com/avito-internships/test-backend-1-mmms914/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, specs
func (_m *Service) Create(ctx context.Context, specs *domain.RoomInitSpecs) (*domain.Room, error) {
	ret := _m.Called(ctx, specs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RoomInitSpecs) (*domain.Room, error)); ok {
		return rf(ctx, specs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RoomInitSpecs) *domain.Room); ok {
		r0 = rf(ctx, specs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RoomInitSpecs) error); ok {
		r1 = rf(ctx, specs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *Service) GetAll(ctx context.Context) ([]*domain.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
